name: push to dev environment
on:
  push:
    branches: ["dev"]
  # pull_request:
  #   branches: ["develop"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v3
      - name: setup node 18.x 
        uses: actions/setup-node@v3
        with:
          node-version: 18
          ## this setup is for node_modules caching 
          ## see more at https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      # cache globally, not only node_modules
      # so we need to run this extra step to see if any missing modules
      - name: install missing modules if any 
        run: yarn # add `--omit=dev` in case of release
      - name: ✅ Lint
        run: yarn lint
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v3
      - name: setup node 18.x 
        uses: actions/setup-node@v3
        with:
          node-version: 18
          ## this setup is for node_modules caching 
          ## see more at https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      # cache globally, not only node_modules
      # so we need to run this extra step to see if any missing modules
      - name: install missing modules if any 
        run: yarn # add `--omit=dev` in case of release
      - name: ✅ Lint
        run: yarn test:unit:once
